<script setup lang="ts">
import { ref } from "vue";
import { BlessDiff, BlessSwitch } from "blessing-ui";

const split = ref(false);
const before = `import { createApp } from "vue";
import App from "./App.vue";

const app = createApp(App);
app.use(router);
app.mount("#app");

// 12 more lines of setup
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...

export default app;
`;
const after = `import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";

const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount("#app");

// 12 more lines of setup
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...

export { app };
`;
</script>

<template>
  <div class="col">
    <BlessSwitch v-model="split">Side by side</BlessSwitch>
    <BlessDiff
      :a="before"
      :b="after"
      :mode="split ? 'split' : 'inline'"
      :context="2"
      label="main.ts"
    />
  </div>
</template>
