// Sidebar groups + one-liners. Extra names = components documented on the same page.
export interface Entry {
  name: string;
  slug: string;
  text: string;
  also?: string[];
}
export const groups: { title: string; items: Entry[] }[] = [
  {
    title: "Primitives",
    items: [
      { name: "BlessChip", slug: "chip", text: "Removable pill" },
      { name: "BlessMeterGroup", slug: "meter-group", text: "Multi-segment meter with legend" },
      { name: "BlessBlockUI", slug: "block-ui", text: "Overlay that blocks its content" },
      {
        name: "BlessWatermarkOverlay",
        slug: "watermark-overlay",
        text: "Tiled text watermark over content",
      },
      { name: "BlessMockup", slug: "mockup", text: "Browser / window / phone frame" },
      {
        name: "BlessIndicator",
        slug: "indicator",
        text: "Count or dot badge anchored on any element",
      },
      { name: "BlessTimeline", slug: "timeline", text: "Vertical rail of dated events" },
      { name: "BlessSwap", slug: "swap", text: "Two-face toggle (icon swap)" },
      { name: "BlessSkew", slug: "skew", text: "Skewed container, counter-skews its slot" },
      { name: "BlessButton", slug: "button", text: "Button or anchor" },
      { name: "BlessBadge", slug: "badge", text: "Small pill" },
      { name: "BlessDash", slug: "dash", text: "Inline 10\u00d71px separator" },
      { name: "BlessSeparator", slug: "separator", text: "`<hr>` / vertical rule, optional label" },
      { name: "BlessIcon", slug: "icon", text: "SVG slot wrapper" },
      { name: "BlessText", slug: "text", text: "Typography helper" },
      { name: "BlessKbd", slug: "kbd", text: "Key combo" },
      { name: "BlessThemeToggle", slug: "theme-toggle", text: "Light/dark switch or 3-way group" },
      { name: "BlessSpinner", slug: "spinner", text: "Loading indicator (`role=status`)" },
      { name: "BlessEmpty", slug: "empty", text: "Empty state" },
      { name: "BlessButtonGroup", slug: "button-group", text: "Joined buttons" },
      { name: "BlessItem", slug: "item", text: "Media + title + description + actions" },
      { name: "BlessAvatar", slug: "avatar", text: "Image with initials fallback" },
      { name: "BlessSkeleton", slug: "skeleton", text: "Shimmer placeholder" },
      { name: "BlessAspectRatio", slug: "aspect-ratio", text: "Ratio box" },
      { name: "BlessProgress", slug: "progress", text: "Bar, determinate or not" },
      { name: "BlessAlert", slug: "alert", text: "Inline notice" },
    ],
  },
  {
    title: "Forms",
    items: [
      {
        name: "BlessCascadeSelect",
        slug: "cascade-select",
        text: "Nested options, one column per level",
      },
      {
        name: "BlessTreeSelect",
        slug: "tree-select",
        text: "Tree in a popover, single or multiple",
      },
      {
        name: "BlessInputNumber",
        slug: "input-number",
        text: "Number with ± steppers and Intl format",
      },
      {
        name: "BlessPasswordInput",
        slug: "password-input",
        text: "Password with reveal toggle and meter",
      },
      { name: "BlessInputTags", slug: "input-tags", text: "Free-text tags" },
      { name: "BlessFloatLabel", slug: "float-label", text: "Floating / in-field label wrapper" },
      { name: "BlessFieldset", slug: "fieldset", text: "Legend group, toggleable" },
      { name: "BlessInplace", slug: "inplace", text: "Click-to-edit" },
      { name: "BlessCompare", slug: "compare", text: "Before / after slider" },
      {
        name: "BlessEditor",
        slug: "editor",
        text: "Rich text: skewed toolbar around a Tiptap editor",
      },
      { name: "BlessKnob", slug: "knob", text: "Rotary dial on a native range input" },
      { name: "BlessSignaturePad", slug: "signature-pad", text: "Draw a signature on canvas" },
      { name: "BlessInputMask", slug: "input-mask", text: "Pattern-masked input (# A *)" },
      { name: "BlessOrderList", slug: "order-list", text: "Drag / button / Alt+arrow reorder" },
      { name: "BlessPickList", slug: "pick-list", text: "Two listboxes with transfer buttons" },
      { name: "BlessRating", slug: "rating", text: "Star rating on native radios" },
      { name: "BlessFileInput", slug: "file-input", text: "Native file input with drop zone" },
      { name: "BlessColorPicker", slug: "color-picker", text: "Native colour input + swatches" },
      { name: "BlessPasswordMeter", slug: "password-meter", text: "Strength meter from rules" },
      { name: "BlessListbox", slug: "listbox", text: "Single / multi select list, role=listbox" },
      { name: "BlessLabel", slug: "label", text: "`<label>` with required mark and hint" },
      { name: "BlessInput", slug: "input", text: "Text-like input" },
      {
        name: "BlessInputGroup",
        slug: "input-group",
        text: "Shared surface: addons + any control",
      },
      { name: "BlessTextarea", slug: "textarea", text: "Auto-growing textarea" },
      { name: "BlessCheckbox", slug: "checkbox", text: "Native checkbox" },
      { name: "BlessRadioGroup", slug: "radio-group", text: "Native radios", also: ["BlessRadio"] },
      { name: "BlessSwitch", slug: "switch", text: "`role=switch` toggle" },
      { name: "BlessSelect", slug: "select", text: "Styled native `<select>`" },
      { name: "BlessSlider", slug: "slider", text: "Native range" },
      { name: "BlessToggle", slug: "toggle", text: "Pressed buttons", also: ["BlessToggleGroup"] },
      { name: "BlessCombobox", slug: "combobox", text: "Searchable select" },
      { name: "BlessDatePicker", slug: "date-picker", text: "Calendar in a popover" },
      { name: "BlessCalendar", slug: "calendar", text: "Month grid" },
      { name: "BlessInputOTP", slug: "input-otp", text: "One-time code cells" },
      {
        name: "BlessForm",
        slug: "form",
        text: "Constraint-API form + field wiring",
        also: ["BlessField"],
      },
    ],
  },
  {
    title: "Layout & navigation",
    items: [
      { name: "BlessTreeTable", slug: "tree-table", text: "Expandable rows on BlessTable" },
      {
        name: "BlessOrgChart",
        slug: "org-chart",
        text: "Node tree with connectors",
        also: ["BlessOrgChartNode"],
      },
      { name: "BlessToolbar", slug: "toolbar", text: "Start / center / end bar" },
      { name: "BlessPanel", slug: "panel", text: "Titled box with actions, toggleable" },
      { name: "BlessStepper", slug: "stepper", text: "Steps header + panels + next / back" },
      { name: "BlessSplitButton", slug: "split-button", text: "Button with a menu half" },
      { name: "BlessDataView", slug: "data-view", text: "List / grid with pagination" },
      {
        name: "BlessDeferredContent",
        slug: "deferred-content",
        text: "Render when scrolled into view",
      },
      {
        name: "BlessBottomTabs",
        slug: "bottom-tabs",
        text: "Mobile bottom nav bar or floating dock",
      },
      { name: "BlessSpeedDial", slug: "speed-dial", text: "FAB with fan-out actions" },
      {
        name: "BlessVirtualScroller",
        slug: "virtual-scroller",
        text: "Windowed list for long data",
      },
      { name: "BlessSteps", slug: "steps", text: "Stepper with done / current / upcoming" },
      { name: "BlessContainer", slug: "container", text: "Centred max-width box" },
      { name: "BlessStack", slug: "stack", text: "Flex row / column with token gap" },
      { name: "BlessScrollTop", slug: "scroll-top", text: "Back-to-top button past a threshold" },
      {
        name: "BlessTree",
        slug: "tree",
        text: "Nested details tree, role=tree",
        also: ["BlessTreeItem"],
      },
      { name: "BlessStage", slug: "stage", text: "Page shell, sidebar \u2192 drawer under 800px" },
      { name: "BlessSidebarNav", slug: "sidebar-nav", text: "Vertical nav list" },
      { name: "BlessNavigationMenu", slug: "navigation-menu", text: "Horizontal nav with panels" },
      { name: "BlessMenubar", slug: "menubar", text: "Bar of `BlessDropdownMenu`s" },
      { name: "BlessBreadcrumb", slug: "breadcrumb", text: "Trail" },
      { name: "BlessPagination", slug: "pagination", text: "Page list" },
      { name: "BlessTabs", slug: "tabs", text: "ARIA tablist" },
      {
        name: "BlessSection",
        slug: "section",
        text: "Titled block with giant skewed word",
        also: ["BlessWatermark"],
      },
      { name: "BlessBackground", slug: "background", text: "Tiled texture layer" },
      { name: "BlessCard", slug: "card", text: "Flat surface" },
      { name: "BlessList", slug: "list", text: "Divided rows", also: ["BlessListItem"] },
      { name: "BlessCollapsible", slug: "collapsible", text: "`<details>` based" },
      { name: "BlessScrollArea", slug: "scroll-area", text: "Thin scrollbar + fade" },
      { name: "BlessResizable", slug: "resizable", text: "Two-pane split" },
      { name: "BlessTable", slug: "table", text: "Typed table, stacks on mobile" },
      { name: "BlessDataTable", slug: "data-table", text: "Table + sort/search/select/paginate" },
    ],
  },
  {
    title: "Overlays",
    items: [
      { name: "BlessDialogHost", slug: "dialog-host", text: "Programmatic modals via useDialog()" },
      { name: "BlessConfirmPopup", slug: "confirm-popup", text: "Confirm inside a popover" },
      { name: "BlessTour", slug: "tour", text: "Step-by-step spotlight walkthrough" },
      { name: "BlessModal", slug: "modal", text: "Native `<dialog>`" },
      { name: "BlessAlertDialog", slug: "alert-dialog", text: "Confirm dialog" },
      { name: "BlessSheet", slug: "sheet", text: "Side panel" },
      { name: "BlessDrawer", slug: "drawer", text: "Bottom sheet with swipe-to-close" },
      { name: "BlessPopover", slug: "popover", text: "Popover API panel" },
      { name: "BlessTooltip", slug: "tooltip", text: "Hover/focus tip" },
      { name: "BlessHoverCard", slug: "hover-card", text: "Rich hover popover" },
      { name: "BlessDropdownMenu", slug: "dropdown-menu", text: "ARIA menu" },
      { name: "BlessContextMenu", slug: "context-menu", text: "Menu on right click" },
      { name: "BlessCommand", slug: "command", text: "\u2318K palette" },
      { name: "BlessGallery", slug: "gallery", text: "Thumb grid + lightbox" },
      { name: "BlessToaster", slug: "toaster", text: "Notifications" },
      { name: "BlessSplash", slug: "splash", text: "First-visit overlay" },
    ],
  },
  {
    title: "Conversation",
    items: [
      { name: "BlessMessage", slug: "message", text: "Avatar + header + content + footer row" },
      { name: "BlessBubble", slug: "bubble", text: "Message bubble" },
      { name: "BlessMarker", slug: "marker", text: "Inline status / note / separator / row" },
      { name: "BlessAttachment", slug: "attachment", text: "File / image chip" },
      { name: "BlessMessageScroller", slug: "message-scroller", text: "Chat viewport" },
      {
        name: "BlessQuestionnaire",
        slug: "questionnaire",
        text: "Multi-step single/multiple/freeform",
      },
    ],
  },
  {
    title: "Chart",
    items: [
      { name: "BlessQrCode", slug: "qr-code", text: "QR code SVG from a module matrix (uqr)" },
      {
        name: "BlessChart",
        slug: "chart",
        text: "Themed frame for any [Unovis](https://unovis.dev) chart",
      },
    ],
  },
  {
    title: "Media",
    items: [
      { name: "BlessCarousel", slug: "carousel", text: "Scroll-snap slider" },
      { name: "BlessAudioPlayer", slug: "audio-player", text: "Track list player" },
    ],
  },
];
